### ISSUE TITLE
MRZInfo doesnt equal

### ISSUE THREAD

**Issue by gurkanlus** [mercuriete/android-mrz-reader#10]
I have an Id whose first line has "<" character after document number. after that it has an id number but mrzinfo consructor doesnt accept that . after remove that character and adds the end of first line it accepts. what can I do?

**Comment by mercuriete** [comment]
MRZInfo is a library of java.

MRZInfo should accept 3 lines MRZ and 2 lines MRZ. So if you think there are something wrong you can fill a bug here: https://sourceforge.net/p/jmrtd/bugs/

If you think the version I am using is too old, you can change the title of this bug to update the dependencies.

Thanks.

**Comment by mercuriete** [comment]
You can check of JMRTD here:

https://github.com/mercuriete/android-mrz-reader/blob/master/MRZReader/build.gradle#L31

**Comment by mercuriete** [comment]
@gurkanlus 
you are right. my code never checed the checksum digits.

I am trying to check at least the checkdigit of the MRZ.

thanks for the report.

**Comment by mercuriete** [comment]
this issue should be fixed with #47 

Remember that checksum only checks documentNumber, birthDate, expirationDate and entire 2nd line on 2 lines MRZs and 2nd line on 3 lines MRZs

So name and surname for example is not checked.

for perfect MRZ read you need to access the passport chip using BAC and NFC.

you can check another project in this url: https://github.com/mercuriete/ajmrtd2

perfect reads on MRZ with OCR is imposible due design limitations.

thank for your report.
