### ISSUE TITLE
Taking lot of time to scan

### ISSUE THREAD

**Issue by supportreq** [mercuriete/android-mrz-reader#5]
I am trying this library, but it seems to take ages for the scan to complete.. please suggest..

**Comment by mercuriete** [comment]
hi @supportreq 
This is a prof of concept using open source OCR called tesseract.

I know that limitation...

You can try cropping the image to small sizes and forcing not to use big resolution camera capture modes.

This project is a spare time project so i will update it on "best effort".

**Comment by mercuriete** [comment]
@supportreq 
In my fancy Samsung Galaxy S9+ it takes less than 500ms

So as I am not implementing a new OCR algorithm because is a dependency...
My answer for this problem is... just buy a better phone.

If you think this is not a propper answer, please reopen this issue.

Thanks for using this project.
